language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
# Only build for commits in PRs for the master branch
branches:
  only:
    master
script:
  - cargo fmt --all -- --check --verbose
  - cargo test --verbose --all
