# docker-rmi
# Autogenerated from man page docker-rmi.1
complete -c docker-rmi -s f -l force --description '    Force removal of the image.'
complete -c docker-rmi -s h -l help --description '    help for rmi.'
complete -c docker-rmi -l no-prune --description '    Do not delete untagged parents SEE ALSO.'
