# qelectrotech
# Autogenerated from man page qelectrotech.1
complete -c qelectrotech -l common-elements-dir --description 'Utilise le dossier REP comme racine de la collection d\'éléments commune.'
complete -c qelectrotech -l config-dir --description 'Utilise le dossier REP comme dossier de configuration de l\'utilisateur couran…'
complete -c qelectrotech -l lang-dir --description 'Recherche les fichiers de traduction de l\'application dans le dossier REP.'
complete -c qelectrotech -l help --description 'Affiche une courte description des options disponibles.'
complete -c qelectrotech -s v -l version --description 'Affiche la version de l\'application (exemple : 0. 1).'
complete -c qelectrotech -l license --description 'Affiche la licence de l\'application (GNU/GPL).'
