name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Formatting
      run: cargo fmt --all -- --check --verbose
    - name: Run tests
      run: cargo test --verbose
